languageCode = "en-us"
title = "FRHS Girls Soccer"
theme = "ananke"
baseURL = "/"

[params]
  favicon = "images/favicon.png"
  twitter = "https://twitter.com/soccerfossil"
  instagram = "https://www.instagram.com/fossilridgesoccer/"
  description = "Home of FRHS Girls Soccer"
