languageCode: "en-us"
title: "FRHS Girls Soccer"
theme: "ananke"
baseURL: "/"
enableGitInfo: true

params:
  favicon: "images/favicon.png"
  twitter: "https://twitter.com/soccerfossil"
  instagram: "https://www.instagram.com/fossilridgesoccer/"
  description: "Home of FRHS Girls Soccer"

outputs:
  home:
  - HTML
  - Calendar
  - RSS
  page:
  - HTML
  - Calendar
  section:
  - HTML
  - Calendar
