baseURL = "https://frhs.soccer/"
languageCode = "en-us"
title = "FRHS Girls Soccer"
theme = "ananke"

[params]
  favicon = "images/favicon.png"
  twitter = "https://twitter.com/soccerfossil"
  instagram = "https://www.instagram.com/fossilridgesoccer/"
  description = "Home of the FRHS Girls Soccer"
